apiVersion: apps/v1
kind: Deployment
metadata:
  name: web2-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web2
  template:
    metadata:
      labels:
        app: web2
    spec:
      containers:
      - name: web2
        image: hiumonday/web2 
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: web2-service
spec:
  type: NodePort
  selector:
    app: web2
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30082